// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connections.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createConnection = `-- name: CreateConnection :one
INSERT INTO pms.connections (
    id, org_id, provider, name, status, secret_ref, config
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, org_id, provider, name, status, secret_ref, config, last_sync_at, last_error, created_at, updated_at
`

type CreateConnectionParams struct {
	ID        uuid.UUID `json:"id"`
	OrgID     uuid.UUID `json:"org_id"`
	Provider  string    `json:"provider"`
	Name      string    `json:"name"`
	Status    string    `json:"status"`
	SecretRef *string   `json:"secret_ref"`
	Config    []byte    `json:"config"`
}

func (q *Queries) CreateConnection(ctx context.Context, arg CreateConnectionParams) (PmsConnection, error) {
	row := q.db.QueryRow(ctx, createConnection,
		arg.ID,
		arg.OrgID,
		arg.Provider,
		arg.Name,
		arg.Status,
		arg.SecretRef,
		arg.Config,
	)
	var i PmsConnection
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.Name,
		&i.Status,
		&i.SecretRef,
		&i.Config,
		&i.LastSyncAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConnection = `-- name: DeleteConnection :exec
DELETE FROM pms.connections WHERE id = $1
`

func (q *Queries) DeleteConnection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteConnection, id)
	return err
}

const getConnection = `-- name: GetConnection :one
SELECT id, org_id, provider, name, status, secret_ref, config, last_sync_at, last_error, created_at, updated_at
  FROM pms.connections
 WHERE id = $1
`

func (q *Queries) GetConnection(ctx context.Context, id uuid.UUID) (PmsConnection, error) {
	row := q.db.QueryRow(ctx, getConnection, id)
	var i PmsConnection
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.Name,
		&i.Status,
		&i.SecretRef,
		&i.Config,
		&i.LastSyncAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConnectionsByOrg = `-- name: ListConnectionsByOrg :many
SELECT id, org_id, provider, name, status, secret_ref, config, last_sync_at, last_error, created_at, updated_at
  FROM pms.connections
 WHERE org_id = $1
 ORDER BY created_at DESC
`

func (q *Queries) ListConnectionsByOrg(ctx context.Context, orgID uuid.UUID) ([]PmsConnection, error) {
	rows, err := q.db.Query(ctx, listConnectionsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PmsConnection{}
	for rows.Next() {
		var i PmsConnection
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Provider,
			&i.Name,
			&i.Status,
			&i.SecretRef,
			&i.Config,
			&i.LastSyncAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConnectionLastSync = `-- name: UpdateConnectionLastSync :exec
UPDATE pms.connections
   SET last_sync_at = $1,
       last_error = NULL,
       updated_at = now()
 WHERE id = $2
`

type UpdateConnectionLastSyncParams struct {
	LastSyncAt pgtype.Timestamptz `json:"last_sync_at"`
	ID         uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateConnectionLastSync(ctx context.Context, arg UpdateConnectionLastSyncParams) error {
	_, err := q.db.Exec(ctx, updateConnectionLastSync, arg.LastSyncAt, arg.ID)
	return err
}

const updateConnectionStatus = `-- name: UpdateConnectionStatus :exec
UPDATE pms.connections
   SET status = $1,
       last_error = $2,
       updated_at = now()
 WHERE id = $3
`

type UpdateConnectionStatusParams struct {
	Status    string    `json:"status"`
	LastError *string   `json:"last_error"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) UpdateConnectionStatus(ctx context.Context, arg UpdateConnectionStatusParams) error {
	_, err := q.db.Exec(ctx, updateConnectionStatus, arg.Status, arg.LastError, arg.ID)
	return err
}
