// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgstore

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PmsConnection struct {
	ID         uuid.UUID          `json:"id"`
	OrgID      uuid.UUID          `json:"org_id"`
	Provider   string             `json:"provider"`
	Name       string             `json:"name"`
	Status     string             `json:"status"`
	SecretRef  *string            `json:"secret_ref"`
	Config     []byte             `json:"config"`
	LastSyncAt pgtype.Timestamptz `json:"last_sync_at"`
	LastError  *string            `json:"last_error"`
	CreatedAt  time.Time          `json:"created_at"`
	UpdatedAt  time.Time          `json:"updated_at"`
}

type PmsProperty struct {
	ID           uuid.UUID   `json:"id"`
	OrgID        uuid.UUID   `json:"org_id"`
	ConnectionID pgtype.UUID `json:"connection_id"`
	ExternalID   *string     `json:"external_id"`
	Name         string      `json:"name"`
	Timezone     string      `json:"timezone"`
	Currency     string      `json:"currency"`
	Address      []byte      `json:"address"`
	IsActive     bool        `json:"is_active"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type PmsRoom struct {
	ID         uuid.UUID `json:"id"`
	OrgID      uuid.UUID `json:"org_id"`
	PropertyID uuid.UUID `json:"property_id"`
	RoomTypeID uuid.UUID `json:"room_type_id"`
	ExternalID string    `json:"external_id"`
	Name       string    `json:"name"`
	IsActive   bool      `json:"is_active"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type PmsRoomType struct {
	ID            uuid.UUID `json:"id"`
	OrgID         uuid.UUID `json:"org_id"`
	PropertyID    uuid.UUID `json:"property_id"`
	ExternalID    *string   `json:"external_id"`
	Code          string    `json:"code"`
	Name          string    `json:"name"`
	Description   *string   `json:"description"`
	Capacity      int32     `json:"capacity"`
	BaseOccupancy int32     `json:"base_occupancy"`
	IsActive      bool      `json:"is_active"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}
