// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: properties.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getProperty = `-- name: GetProperty :one
SELECT id, org_id, connection_id, external_id, name, timezone, currency, address, is_active, created_at, updated_at
  FROM pms.properties
 WHERE id = $1
`

func (q *Queries) GetProperty(ctx context.Context, id uuid.UUID) (PmsProperty, error) {
	row := q.db.QueryRow(ctx, getProperty, id)
	var i PmsProperty
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ConnectionID,
		&i.ExternalID,
		&i.Name,
		&i.Timezone,
		&i.Currency,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPropertyByExternal = `-- name: GetPropertyByExternal :one
SELECT id, org_id, connection_id, external_id, name, timezone, currency, address, is_active, created_at, updated_at
  FROM pms.properties
 WHERE org_id = $1
   AND external_id = $2
`

type GetPropertyByExternalParams struct {
	OrgID      uuid.UUID `json:"org_id"`
	ExternalID *string   `json:"external_id"`
}

func (q *Queries) GetPropertyByExternal(ctx context.Context, arg GetPropertyByExternalParams) (PmsProperty, error) {
	row := q.db.QueryRow(ctx, getPropertyByExternal, arg.OrgID, arg.ExternalID)
	var i PmsProperty
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ConnectionID,
		&i.ExternalID,
		&i.Name,
		&i.Timezone,
		&i.Currency,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProperty = `-- name: InsertProperty :one
INSERT INTO pms.properties (
    id, org_id, connection_id, external_id, name, timezone, currency, address, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, org_id, connection_id, external_id, name, timezone, currency, address, is_active, created_at, updated_at
`

type InsertPropertyParams struct {
	ID           uuid.UUID   `json:"id"`
	OrgID        uuid.UUID   `json:"org_id"`
	ConnectionID pgtype.UUID `json:"connection_id"`
	ExternalID   *string     `json:"external_id"`
	Name         string      `json:"name"`
	Timezone     string      `json:"timezone"`
	Currency     string      `json:"currency"`
	Address      []byte      `json:"address"`
	IsActive     bool        `json:"is_active"`
}

func (q *Queries) InsertProperty(ctx context.Context, arg InsertPropertyParams) (PmsProperty, error) {
	row := q.db.QueryRow(ctx, insertProperty,
		arg.ID,
		arg.OrgID,
		arg.ConnectionID,
		arg.ExternalID,
		arg.Name,
		arg.Timezone,
		arg.Currency,
		arg.Address,
		arg.IsActive,
	)
	var i PmsProperty
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ConnectionID,
		&i.ExternalID,
		&i.Name,
		&i.Timezone,
		&i.Currency,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPropertiesByConnection = `-- name: ListPropertiesByConnection :many
SELECT id, org_id, connection_id, external_id, name, timezone, currency, address, is_active, created_at, updated_at
  FROM pms.properties
 WHERE connection_id = $1
   AND is_active = TRUE
 ORDER BY name
`

func (q *Queries) ListPropertiesByConnection(ctx context.Context, connectionID pgtype.UUID) ([]PmsProperty, error) {
	rows, err := q.db.Query(ctx, listPropertiesByConnection, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PmsProperty{}
	for rows.Next() {
		var i PmsProperty
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ConnectionID,
			&i.ExternalID,
			&i.Name,
			&i.Timezone,
			&i.Currency,
			&i.Address,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPropertiesByOrg = `-- name: ListPropertiesByOrg :many
SELECT id, org_id, connection_id, external_id, name, timezone, currency, address, is_active, created_at, updated_at
  FROM pms.properties
 WHERE org_id = $1
   AND is_active = TRUE
 ORDER BY name
`

func (q *Queries) ListPropertiesByOrg(ctx context.Context, orgID uuid.UUID) ([]PmsProperty, error) {
	rows, err := q.db.Query(ctx, listPropertiesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PmsProperty{}
	for rows.Next() {
		var i PmsProperty
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ConnectionID,
			&i.ExternalID,
			&i.Name,
			&i.Timezone,
			&i.Currency,
			&i.Address,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProperty = `-- name: UpdateProperty :one
UPDATE pms.properties
   SET name = $1,
       timezone = $2,
       currency = $3,
       address = $4,
       is_active = $5,
       connection_id = $6,
       updated_at = now()
 WHERE id = $7
RETURNING id, org_id, connection_id, external_id, name, timezone, currency, address, is_active, created_at, updated_at
`

type UpdatePropertyParams struct {
	Name         string      `json:"name"`
	Timezone     string      `json:"timezone"`
	Currency     string      `json:"currency"`
	Address      []byte      `json:"address"`
	IsActive     bool        `json:"is_active"`
	ConnectionID pgtype.UUID `json:"connection_id"`
	ID           uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateProperty(ctx context.Context, arg UpdatePropertyParams) (PmsProperty, error) {
	row := q.db.QueryRow(ctx, updateProperty,
		arg.Name,
		arg.Timezone,
		arg.Currency,
		arg.Address,
		arg.IsActive,
		arg.ConnectionID,
		arg.ID,
	)
	var i PmsProperty
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ConnectionID,
		&i.ExternalID,
		&i.Name,
		&i.Timezone,
		&i.Currency,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
