// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: room_types.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const getRoomTypeByCode = `-- name: GetRoomTypeByCode :one
SELECT id, org_id, property_id, external_id, code, name, description, capacity, base_occupancy, is_active, created_at, updated_at
  FROM pms.room_types
 WHERE property_id = $1
   AND code = $2
`

type GetRoomTypeByCodeParams struct {
	PropertyID uuid.UUID `json:"property_id"`
	Code       string    `json:"code"`
}

func (q *Queries) GetRoomTypeByCode(ctx context.Context, arg GetRoomTypeByCodeParams) (PmsRoomType, error) {
	row := q.db.QueryRow(ctx, getRoomTypeByCode, arg.PropertyID, arg.Code)
	var i PmsRoomType
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.PropertyID,
		&i.ExternalID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Capacity,
		&i.BaseOccupancy,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoomTypeByExternal = `-- name: GetRoomTypeByExternal :one
SELECT id, org_id, property_id, external_id, code, name, description, capacity, base_occupancy, is_active, created_at, updated_at
  FROM pms.room_types
 WHERE property_id = $1
   AND external_id = $2
`

type GetRoomTypeByExternalParams struct {
	PropertyID uuid.UUID `json:"property_id"`
	ExternalID *string   `json:"external_id"`
}

func (q *Queries) GetRoomTypeByExternal(ctx context.Context, arg GetRoomTypeByExternalParams) (PmsRoomType, error) {
	row := q.db.QueryRow(ctx, getRoomTypeByExternal, arg.PropertyID, arg.ExternalID)
	var i PmsRoomType
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.PropertyID,
		&i.ExternalID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Capacity,
		&i.BaseOccupancy,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRoomType = `-- name: InsertRoomType :one
INSERT INTO pms.room_types (
    id, org_id, property_id, external_id, code, name, description, capacity, base_occupancy, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, org_id, property_id, external_id, code, name, description, capacity, base_occupancy, is_active, created_at, updated_at
`

type InsertRoomTypeParams struct {
	ID            uuid.UUID `json:"id"`
	OrgID         uuid.UUID `json:"org_id"`
	PropertyID    uuid.UUID `json:"property_id"`
	ExternalID    *string   `json:"external_id"`
	Code          string    `json:"code"`
	Name          string    `json:"name"`
	Description   *string   `json:"description"`
	Capacity      int32     `json:"capacity"`
	BaseOccupancy int32     `json:"base_occupancy"`
	IsActive      bool      `json:"is_active"`
}

func (q *Queries) InsertRoomType(ctx context.Context, arg InsertRoomTypeParams) (PmsRoomType, error) {
	row := q.db.QueryRow(ctx, insertRoomType,
		arg.ID,
		arg.OrgID,
		arg.PropertyID,
		arg.ExternalID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Capacity,
		arg.BaseOccupancy,
		arg.IsActive,
	)
	var i PmsRoomType
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.PropertyID,
		&i.ExternalID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Capacity,
		&i.BaseOccupancy,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoomTypesByProperty = `-- name: ListRoomTypesByProperty :many
SELECT id, org_id, property_id, external_id, code, name, description, capacity, base_occupancy, is_active, created_at, updated_at
  FROM pms.room_types
 WHERE property_id = $1
   AND is_active = TRUE
 ORDER BY name
`

func (q *Queries) ListRoomTypesByProperty(ctx context.Context, propertyID uuid.UUID) ([]PmsRoomType, error) {
	rows, err := q.db.Query(ctx, listRoomTypesByProperty, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PmsRoomType{}
	for rows.Next() {
		var i PmsRoomType
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.PropertyID,
			&i.ExternalID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Capacity,
			&i.BaseOccupancy,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoomType = `-- name: UpdateRoomType :one
UPDATE pms.room_types
   SET external_id = $1,
       name = $2,
       description = $3,
       capacity = $4,
       base_occupancy = $5,
       is_active = $6,
       updated_at = now()
 WHERE id = $7
RETURNING id, org_id, property_id, external_id, code, name, description, capacity, base_occupancy, is_active, created_at, updated_at
`

type UpdateRoomTypeParams struct {
	ExternalID    *string   `json:"external_id"`
	Name          string    `json:"name"`
	Description   *string   `json:"description"`
	Capacity      int32     `json:"capacity"`
	BaseOccupancy int32     `json:"base_occupancy"`
	IsActive      bool      `json:"is_active"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) UpdateRoomType(ctx context.Context, arg UpdateRoomTypeParams) (PmsRoomType, error) {
	row := q.db.QueryRow(ctx, updateRoomType,
		arg.ExternalID,
		arg.Name,
		arg.Description,
		arg.Capacity,
		arg.BaseOccupancy,
		arg.IsActive,
		arg.ID,
	)
	var i PmsRoomType
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.PropertyID,
		&i.ExternalID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Capacity,
		&i.BaseOccupancy,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
