// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const listRoomsByProperty = `-- name: ListRoomsByProperty :many
SELECT id, org_id, property_id, room_type_id, external_id, name, is_active, created_at, updated_at FROM pms.rooms
WHERE property_id = $1 AND is_active = TRUE
ORDER BY name ASC
`

func (q *Queries) ListRoomsByProperty(ctx context.Context, propertyID uuid.UUID) ([]PmsRoom, error) {
	rows, err := q.db.Query(ctx, listRoomsByProperty, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PmsRoom{}
	for rows.Next() {
		var i PmsRoom
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.PropertyID,
			&i.RoomTypeID,
			&i.ExternalID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomsByRoomType = `-- name: ListRoomsByRoomType :many
SELECT id, org_id, property_id, room_type_id, external_id, name, is_active, created_at, updated_at FROM pms.rooms
WHERE room_type_id = $1 AND is_active = TRUE
ORDER BY name ASC
`

func (q *Queries) ListRoomsByRoomType(ctx context.Context, roomTypeID uuid.UUID) ([]PmsRoom, error) {
	rows, err := q.db.Query(ctx, listRoomsByRoomType, roomTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PmsRoom{}
	for rows.Next() {
		var i PmsRoom
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.PropertyID,
			&i.RoomTypeID,
			&i.ExternalID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRoom = `-- name: UpsertRoom :one
INSERT INTO pms.rooms (
    org_id, property_id, room_type_id, external_id, name, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (org_id, property_id, external_id) DO UPDATE SET
    room_type_id = EXCLUDED.room_type_id,
    name = EXCLUDED.name,
    is_active = EXCLUDED.is_active,
    updated_at = now()
RETURNING id, org_id, property_id, room_type_id, external_id, name, is_active, created_at, updated_at
`

type UpsertRoomParams struct {
	OrgID      uuid.UUID `json:"org_id"`
	PropertyID uuid.UUID `json:"property_id"`
	RoomTypeID uuid.UUID `json:"room_type_id"`
	ExternalID string    `json:"external_id"`
	Name       string    `json:"name"`
	IsActive   bool      `json:"is_active"`
}

func (q *Queries) UpsertRoom(ctx context.Context, arg UpsertRoomParams) (PmsRoom, error) {
	row := q.db.QueryRow(ctx, upsertRoom,
		arg.OrgID,
		arg.PropertyID,
		arg.RoomTypeID,
		arg.ExternalID,
		arg.Name,
		arg.IsActive,
	)
	var i PmsRoom
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.PropertyID,
		&i.RoomTypeID,
		&i.ExternalID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
