// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgstore

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ReservationsGuest struct {
	ID        uuid.UUID `json:"id"`
	OrgID     uuid.UUID `json:"org_id"`
	FirstName *string   `json:"first_name"`
	LastName  *string   `json:"last_name"`
	Email     *string   `json:"email"`
	Phone     *string   `json:"phone"`
	Country   *string   `json:"country"`
	Metadata  []byte    `json:"metadata"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ReservationsReservation struct {
	ID                  uuid.UUID          `json:"id"`
	OrgID               uuid.UUID          `json:"org_id"`
	ChannelConnectionID pgtype.UUID        `json:"channel_connection_id"`
	PropertyID          uuid.UUID          `json:"property_id"`
	ExternalID          *string            `json:"external_id"`
	ConfirmationCode    *string            `json:"confirmation_code"`
	PrimaryGuestID      pgtype.UUID        `json:"primary_guest_id"`
	Status              string             `json:"status"`
	CheckIn             time.Time          `json:"check_in"`
	CheckOut            time.Time          `json:"check_out"`
	Adults              int32              `json:"adults"`
	Children            int32              `json:"children"`
	Currency            string             `json:"currency"`
	TotalAmountMinor    int64              `json:"total_amount_minor"`
	Notes               *string            `json:"notes"`
	Metadata            []byte             `json:"metadata"`
	BookedAt            time.Time          `json:"booked_at"`
	CancelledAt         pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
}
