// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservations.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getReservation = `-- name: GetReservation :one
SELECT id, org_id, channel_connection_id, property_id, external_id, confirmation_code,
       primary_guest_id, status, check_in, check_out, adults, children,
       currency, total_amount_minor, notes, metadata, booked_at, created_at, updated_at
  FROM reservations.reservations
 WHERE id = $1
`

type GetReservationRow struct {
	ID                  uuid.UUID   `json:"id"`
	OrgID               uuid.UUID   `json:"org_id"`
	ChannelConnectionID pgtype.UUID `json:"channel_connection_id"`
	PropertyID          uuid.UUID   `json:"property_id"`
	ExternalID          *string     `json:"external_id"`
	ConfirmationCode    *string     `json:"confirmation_code"`
	PrimaryGuestID      pgtype.UUID `json:"primary_guest_id"`
	Status              string      `json:"status"`
	CheckIn             time.Time   `json:"check_in"`
	CheckOut            time.Time   `json:"check_out"`
	Adults              int32       `json:"adults"`
	Children            int32       `json:"children"`
	Currency            string      `json:"currency"`
	TotalAmountMinor    int64       `json:"total_amount_minor"`
	Notes               *string     `json:"notes"`
	Metadata            []byte      `json:"metadata"`
	BookedAt            time.Time   `json:"booked_at"`
	CreatedAt           time.Time   `json:"created_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
}

func (q *Queries) GetReservation(ctx context.Context, id uuid.UUID) (GetReservationRow, error) {
	row := q.db.QueryRow(ctx, getReservation, id)
	var i GetReservationRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ChannelConnectionID,
		&i.PropertyID,
		&i.ExternalID,
		&i.ConfirmationCode,
		&i.PrimaryGuestID,
		&i.Status,
		&i.CheckIn,
		&i.CheckOut,
		&i.Adults,
		&i.Children,
		&i.Currency,
		&i.TotalAmountMinor,
		&i.Notes,
		&i.Metadata,
		&i.BookedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReservationByExternal = `-- name: GetReservationByExternal :one
SELECT id, org_id, channel_connection_id, property_id, external_id, confirmation_code,
       primary_guest_id, status, check_in, check_out, adults, children,
       currency, total_amount_minor, notes, metadata, booked_at, created_at, updated_at
  FROM reservations.reservations
 WHERE channel_connection_id = $1
   AND external_id = $2
`

type GetReservationByExternalParams struct {
	ChannelConnectionID pgtype.UUID `json:"channel_connection_id"`
	ExternalID          *string     `json:"external_id"`
}

type GetReservationByExternalRow struct {
	ID                  uuid.UUID   `json:"id"`
	OrgID               uuid.UUID   `json:"org_id"`
	ChannelConnectionID pgtype.UUID `json:"channel_connection_id"`
	PropertyID          uuid.UUID   `json:"property_id"`
	ExternalID          *string     `json:"external_id"`
	ConfirmationCode    *string     `json:"confirmation_code"`
	PrimaryGuestID      pgtype.UUID `json:"primary_guest_id"`
	Status              string      `json:"status"`
	CheckIn             time.Time   `json:"check_in"`
	CheckOut            time.Time   `json:"check_out"`
	Adults              int32       `json:"adults"`
	Children            int32       `json:"children"`
	Currency            string      `json:"currency"`
	TotalAmountMinor    int64       `json:"total_amount_minor"`
	Notes               *string     `json:"notes"`
	Metadata            []byte      `json:"metadata"`
	BookedAt            time.Time   `json:"booked_at"`
	CreatedAt           time.Time   `json:"created_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
}

func (q *Queries) GetReservationByExternal(ctx context.Context, arg GetReservationByExternalParams) (GetReservationByExternalRow, error) {
	row := q.db.QueryRow(ctx, getReservationByExternal, arg.ChannelConnectionID, arg.ExternalID)
	var i GetReservationByExternalRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ChannelConnectionID,
		&i.PropertyID,
		&i.ExternalID,
		&i.ConfirmationCode,
		&i.PrimaryGuestID,
		&i.Status,
		&i.CheckIn,
		&i.CheckOut,
		&i.Adults,
		&i.Children,
		&i.Currency,
		&i.TotalAmountMinor,
		&i.Notes,
		&i.Metadata,
		&i.BookedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertGuest = `-- name: InsertGuest :one
INSERT INTO reservations.guests (id, org_id, first_name, last_name, email, phone)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, first_name, last_name, email, phone, created_at, updated_at
`

type InsertGuestParams struct {
	ID        uuid.UUID `json:"id"`
	OrgID     uuid.UUID `json:"org_id"`
	FirstName *string   `json:"first_name"`
	LastName  *string   `json:"last_name"`
	Email     *string   `json:"email"`
	Phone     *string   `json:"phone"`
}

type InsertGuestRow struct {
	ID        uuid.UUID `json:"id"`
	OrgID     uuid.UUID `json:"org_id"`
	FirstName *string   `json:"first_name"`
	LastName  *string   `json:"last_name"`
	Email     *string   `json:"email"`
	Phone     *string   `json:"phone"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) InsertGuest(ctx context.Context, arg InsertGuestParams) (InsertGuestRow, error) {
	row := q.db.QueryRow(ctx, insertGuest,
		arg.ID,
		arg.OrgID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
	)
	var i InsertGuestRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertReservation = `-- name: InsertReservation :one
INSERT INTO reservations.reservations (
    id, org_id, channel_connection_id, property_id, external_id, confirmation_code,
    primary_guest_id, status, check_in, check_out, adults, children,
    currency, total_amount_minor, notes, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16
)
RETURNING id, org_id, channel_connection_id, property_id, external_id, confirmation_code,
          primary_guest_id, status, check_in, check_out, adults, children,
          currency, total_amount_minor, notes, metadata, booked_at, created_at, updated_at
`

type InsertReservationParams struct {
	ID                  uuid.UUID   `json:"id"`
	OrgID               uuid.UUID   `json:"org_id"`
	ChannelConnectionID pgtype.UUID `json:"channel_connection_id"`
	PropertyID          uuid.UUID   `json:"property_id"`
	ExternalID          *string     `json:"external_id"`
	ConfirmationCode    *string     `json:"confirmation_code"`
	PrimaryGuestID      pgtype.UUID `json:"primary_guest_id"`
	Status              string      `json:"status"`
	CheckIn             time.Time   `json:"check_in"`
	CheckOut            time.Time   `json:"check_out"`
	Adults              int32       `json:"adults"`
	Children            int32       `json:"children"`
	Currency            string      `json:"currency"`
	TotalAmountMinor    int64       `json:"total_amount_minor"`
	Notes               *string     `json:"notes"`
	Metadata            []byte      `json:"metadata"`
}

type InsertReservationRow struct {
	ID                  uuid.UUID   `json:"id"`
	OrgID               uuid.UUID   `json:"org_id"`
	ChannelConnectionID pgtype.UUID `json:"channel_connection_id"`
	PropertyID          uuid.UUID   `json:"property_id"`
	ExternalID          *string     `json:"external_id"`
	ConfirmationCode    *string     `json:"confirmation_code"`
	PrimaryGuestID      pgtype.UUID `json:"primary_guest_id"`
	Status              string      `json:"status"`
	CheckIn             time.Time   `json:"check_in"`
	CheckOut            time.Time   `json:"check_out"`
	Adults              int32       `json:"adults"`
	Children            int32       `json:"children"`
	Currency            string      `json:"currency"`
	TotalAmountMinor    int64       `json:"total_amount_minor"`
	Notes               *string     `json:"notes"`
	Metadata            []byte      `json:"metadata"`
	BookedAt            time.Time   `json:"booked_at"`
	CreatedAt           time.Time   `json:"created_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
}

func (q *Queries) InsertReservation(ctx context.Context, arg InsertReservationParams) (InsertReservationRow, error) {
	row := q.db.QueryRow(ctx, insertReservation,
		arg.ID,
		arg.OrgID,
		arg.ChannelConnectionID,
		arg.PropertyID,
		arg.ExternalID,
		arg.ConfirmationCode,
		arg.PrimaryGuestID,
		arg.Status,
		arg.CheckIn,
		arg.CheckOut,
		arg.Adults,
		arg.Children,
		arg.Currency,
		arg.TotalAmountMinor,
		arg.Notes,
		arg.Metadata,
	)
	var i InsertReservationRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ChannelConnectionID,
		&i.PropertyID,
		&i.ExternalID,
		&i.ConfirmationCode,
		&i.PrimaryGuestID,
		&i.Status,
		&i.CheckIn,
		&i.CheckOut,
		&i.Adults,
		&i.Children,
		&i.Currency,
		&i.TotalAmountMinor,
		&i.Notes,
		&i.Metadata,
		&i.BookedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReservationsByProperty = `-- name: ListReservationsByProperty :many
SELECT id, org_id, channel_connection_id, property_id, external_id, confirmation_code,
       primary_guest_id, status, check_in, check_out, adults, children,
       currency, total_amount_minor, notes, metadata, booked_at, created_at, updated_at
  FROM reservations.reservations
 WHERE property_id = $1
 ORDER BY check_in DESC, created_at DESC
`

type ListReservationsByPropertyRow struct {
	ID                  uuid.UUID   `json:"id"`
	OrgID               uuid.UUID   `json:"org_id"`
	ChannelConnectionID pgtype.UUID `json:"channel_connection_id"`
	PropertyID          uuid.UUID   `json:"property_id"`
	ExternalID          *string     `json:"external_id"`
	ConfirmationCode    *string     `json:"confirmation_code"`
	PrimaryGuestID      pgtype.UUID `json:"primary_guest_id"`
	Status              string      `json:"status"`
	CheckIn             time.Time   `json:"check_in"`
	CheckOut            time.Time   `json:"check_out"`
	Adults              int32       `json:"adults"`
	Children            int32       `json:"children"`
	Currency            string      `json:"currency"`
	TotalAmountMinor    int64       `json:"total_amount_minor"`
	Notes               *string     `json:"notes"`
	Metadata            []byte      `json:"metadata"`
	BookedAt            time.Time   `json:"booked_at"`
	CreatedAt           time.Time   `json:"created_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
}

func (q *Queries) ListReservationsByProperty(ctx context.Context, propertyID uuid.UUID) ([]ListReservationsByPropertyRow, error) {
	rows, err := q.db.Query(ctx, listReservationsByProperty, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReservationsByPropertyRow{}
	for rows.Next() {
		var i ListReservationsByPropertyRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ChannelConnectionID,
			&i.PropertyID,
			&i.ExternalID,
			&i.ConfirmationCode,
			&i.PrimaryGuestID,
			&i.Status,
			&i.CheckIn,
			&i.CheckOut,
			&i.Adults,
			&i.Children,
			&i.Currency,
			&i.TotalAmountMinor,
			&i.Notes,
			&i.Metadata,
			&i.BookedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReservation = `-- name: UpdateReservation :one
UPDATE reservations.reservations
   SET status = $2,
       check_in = $3,
       check_out = $4,
       adults = $5,
       children = $6,
       currency = $7,
       total_amount_minor = $8,
       notes = $9,
       metadata = $10,
       updated_at = now()
 WHERE id = $1
RETURNING id, org_id, channel_connection_id, property_id, external_id, confirmation_code,
          primary_guest_id, status, check_in, check_out, adults, children,
          currency, total_amount_minor, notes, metadata, booked_at, created_at, updated_at
`

type UpdateReservationParams struct {
	ID               uuid.UUID `json:"id"`
	Status           string    `json:"status"`
	CheckIn          time.Time `json:"check_in"`
	CheckOut         time.Time `json:"check_out"`
	Adults           int32     `json:"adults"`
	Children         int32     `json:"children"`
	Currency         string    `json:"currency"`
	TotalAmountMinor int64     `json:"total_amount_minor"`
	Notes            *string   `json:"notes"`
	Metadata         []byte    `json:"metadata"`
}

type UpdateReservationRow struct {
	ID                  uuid.UUID   `json:"id"`
	OrgID               uuid.UUID   `json:"org_id"`
	ChannelConnectionID pgtype.UUID `json:"channel_connection_id"`
	PropertyID          uuid.UUID   `json:"property_id"`
	ExternalID          *string     `json:"external_id"`
	ConfirmationCode    *string     `json:"confirmation_code"`
	PrimaryGuestID      pgtype.UUID `json:"primary_guest_id"`
	Status              string      `json:"status"`
	CheckIn             time.Time   `json:"check_in"`
	CheckOut            time.Time   `json:"check_out"`
	Adults              int32       `json:"adults"`
	Children            int32       `json:"children"`
	Currency            string      `json:"currency"`
	TotalAmountMinor    int64       `json:"total_amount_minor"`
	Notes               *string     `json:"notes"`
	Metadata            []byte      `json:"metadata"`
	BookedAt            time.Time   `json:"booked_at"`
	CreatedAt           time.Time   `json:"created_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
}

func (q *Queries) UpdateReservation(ctx context.Context, arg UpdateReservationParams) (UpdateReservationRow, error) {
	row := q.db.QueryRow(ctx, updateReservation,
		arg.ID,
		arg.Status,
		arg.CheckIn,
		arg.CheckOut,
		arg.Adults,
		arg.Children,
		arg.Currency,
		arg.TotalAmountMinor,
		arg.Notes,
		arg.Metadata,
	)
	var i UpdateReservationRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ChannelConnectionID,
		&i.PropertyID,
		&i.ExternalID,
		&i.ConfirmationCode,
		&i.PrimaryGuestID,
		&i.Status,
		&i.CheckIn,
		&i.CheckOut,
		&i.Adults,
		&i.Children,
		&i.Currency,
		&i.TotalAmountMinor,
		&i.Notes,
		&i.Metadata,
		&i.BookedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
