// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listInventoryDays = `-- name: ListInventoryDays :many
SELECT org_id,
       room_type_id,
       stay_date,
       available,
       sold,
       blocked,
       stop_sell,
       min_stay,
       max_stay,
       cta,
       ctd,
       version,
       updated_at
  FROM inventory.inventory_days
 WHERE room_type_id = $1
   AND stay_date BETWEEN $2 AND $3
 ORDER BY stay_date
`

type ListInventoryDaysParams struct {
	RoomTypeID uuid.UUID `json:"room_type_id"`
	FromDate   time.Time `json:"from_date"`
	ToDate     time.Time `json:"to_date"`
}

type ListInventoryDaysRow struct {
	OrgID      uuid.UUID `json:"org_id"`
	RoomTypeID uuid.UUID `json:"room_type_id"`
	StayDate   time.Time `json:"stay_date"`
	Available  int32     `json:"available"`
	Sold       int32     `json:"sold"`
	Blocked    int32     `json:"blocked"`
	StopSell   bool      `json:"stop_sell"`
	MinStay    *int32    `json:"min_stay"`
	MaxStay    *int32    `json:"max_stay"`
	Cta        bool      `json:"cta"`
	Ctd        bool      `json:"ctd"`
	Version    int64     `json:"version"`
	UpdatedAt  time.Time `json:"updated_at"`
}

// Returns all inventory days for a room type within a date range, ordered by date.
func (q *Queries) ListInventoryDays(ctx context.Context, arg ListInventoryDaysParams) ([]ListInventoryDaysRow, error) {
	rows, err := q.db.Query(ctx, listInventoryDays, arg.RoomTypeID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInventoryDaysRow{}
	for rows.Next() {
		var i ListInventoryDaysRow
		if err := rows.Scan(
			&i.OrgID,
			&i.RoomTypeID,
			&i.StayDate,
			&i.Available,
			&i.Sold,
			&i.Blocked,
			&i.StopSell,
			&i.MinStay,
			&i.MaxStay,
			&i.Cta,
			&i.Ctd,
			&i.Version,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertInventoryDay = `-- name: UpsertInventoryDay :one
INSERT INTO inventory.inventory_days (
    org_id, room_type_id, stay_date,
    available, sold, blocked,
    stop_sell, min_stay, max_stay,
    cta, ctd
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11
)
ON CONFLICT (org_id, room_type_id, stay_date) DO UPDATE SET
    available  = EXCLUDED.available,
    sold       = EXCLUDED.sold,
    blocked    = EXCLUDED.blocked,
    stop_sell  = EXCLUDED.stop_sell,
    min_stay   = EXCLUDED.min_stay,
    max_stay   = EXCLUDED.max_stay,
    cta        = EXCLUDED.cta,
    ctd        = EXCLUDED.ctd,
    version    = inventory_days.version + 1,
    updated_at = now()
RETURNING org_id, room_type_id, stay_date, available, sold, blocked,
          stop_sell, min_stay, max_stay, cta, ctd, version, updated_at
`

type UpsertInventoryDayParams struct {
	OrgID      uuid.UUID `json:"org_id"`
	RoomTypeID uuid.UUID `json:"room_type_id"`
	StayDate   time.Time `json:"stay_date"`
	Available  int32     `json:"available"`
	Sold       int32     `json:"sold"`
	Blocked    int32     `json:"blocked"`
	StopSell   bool      `json:"stop_sell"`
	MinStay    *int32    `json:"min_stay"`
	MaxStay    *int32    `json:"max_stay"`
	Cta        bool      `json:"cta"`
	Ctd        bool      `json:"ctd"`
}

type UpsertInventoryDayRow struct {
	OrgID      uuid.UUID `json:"org_id"`
	RoomTypeID uuid.UUID `json:"room_type_id"`
	StayDate   time.Time `json:"stay_date"`
	Available  int32     `json:"available"`
	Sold       int32     `json:"sold"`
	Blocked    int32     `json:"blocked"`
	StopSell   bool      `json:"stop_sell"`
	MinStay    *int32    `json:"min_stay"`
	MaxStay    *int32    `json:"max_stay"`
	Cta        bool      `json:"cta"`
	Ctd        bool      `json:"ctd"`
	Version    int64     `json:"version"`
	UpdatedAt  time.Time `json:"updated_at"`
}

// Inserts or updates a single inventory day, bumping the optimistic version counter.
func (q *Queries) UpsertInventoryDay(ctx context.Context, arg UpsertInventoryDayParams) (UpsertInventoryDayRow, error) {
	row := q.db.QueryRow(ctx, upsertInventoryDay,
		arg.OrgID,
		arg.RoomTypeID,
		arg.StayDate,
		arg.Available,
		arg.Sold,
		arg.Blocked,
		arg.StopSell,
		arg.MinStay,
		arg.MaxStay,
		arg.Cta,
		arg.Ctd,
	)
	var i UpsertInventoryDayRow
	err := row.Scan(
		&i.OrgID,
		&i.RoomTypeID,
		&i.StayDate,
		&i.Available,
		&i.Sold,
		&i.Blocked,
		&i.StopSell,
		&i.MinStay,
		&i.MaxStay,
		&i.Cta,
		&i.Ctd,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}
