// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgstore

import (
	"time"

	"github.com/google/uuid"
)

type InventoryInventoryDay struct {
	OrgID      uuid.UUID `json:"org_id"`
	RoomTypeID uuid.UUID `json:"room_type_id"`
	StayDate   time.Time `json:"stay_date"`
	Available  int32     `json:"available"`
	Sold       int32     `json:"sold"`
	Blocked    int32     `json:"blocked"`
	StopSell   bool      `json:"stop_sell"`
	MinStay    *int32    `json:"min_stay"`
	MaxStay    *int32    `json:"max_stay"`
	Cta        bool      `json:"cta"`
	Ctd        bool      `json:"ctd"`
	Version    int64     `json:"version"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}
