// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (
    id, org_id, property_id, connection_id, provider, external_property_id, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, org_id, property_id, connection_id, provider, external_property_id, status, last_sync_at, last_error, created_at, updated_at
`

type CreateChannelParams struct {
	ID                 uuid.UUID `json:"id"`
	OrgID              uuid.UUID `json:"org_id"`
	PropertyID         uuid.UUID `json:"property_id"`
	ConnectionID       uuid.UUID `json:"connection_id"`
	Provider           string    `json:"provider"`
	ExternalPropertyID string    `json:"external_property_id"`
	Status             string    `json:"status"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.ID,
		arg.OrgID,
		arg.PropertyID,
		arg.ConnectionID,
		arg.Provider,
		arg.ExternalPropertyID,
		arg.Status,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.PropertyID,
		&i.ConnectionID,
		&i.Provider,
		&i.ExternalPropertyID,
		&i.Status,
		&i.LastSyncAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM channels WHERE id = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChannel, id)
	return err
}

const getChannelByID = `-- name: GetChannelByID :one
SELECT id, org_id, property_id, connection_id, provider, external_property_id, status, last_sync_at, last_error, created_at, updated_at FROM channels
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetChannelByID(ctx context.Context, id uuid.UUID) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByID, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.PropertyID,
		&i.ConnectionID,
		&i.Provider,
		&i.ExternalPropertyID,
		&i.Status,
		&i.LastSyncAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChannelsByProperty = `-- name: ListChannelsByProperty :many
SELECT id, org_id, property_id, connection_id, provider, external_property_id, status, last_sync_at, last_error, created_at, updated_at FROM channels
WHERE property_id = $1
ORDER BY created_at
`

func (q *Queries) ListChannelsByProperty(ctx context.Context, propertyID uuid.UUID) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listChannelsByProperty, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.PropertyID,
			&i.ConnectionID,
			&i.Provider,
			&i.ExternalPropertyID,
			&i.Status,
			&i.LastSyncAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChannelLastSync = `-- name: UpdateChannelLastSync :exec
UPDATE channels
SET last_sync_at = $2, updated_at = now()
WHERE id = $1
`

type UpdateChannelLastSyncParams struct {
	ID         uuid.UUID          `json:"id"`
	LastSyncAt pgtype.Timestamptz `json:"last_sync_at"`
}

func (q *Queries) UpdateChannelLastSync(ctx context.Context, arg UpdateChannelLastSyncParams) error {
	_, err := q.db.Exec(ctx, updateChannelLastSync, arg.ID, arg.LastSyncAt)
	return err
}

const updateChannelStatus = `-- name: UpdateChannelStatus :exec
UPDATE channels
SET status = $2, last_error = $3, updated_at = now()
WHERE id = $1
`

type UpdateChannelStatusParams struct {
	ID        uuid.UUID `json:"id"`
	Status    string    `json:"status"`
	LastError *string   `json:"last_error"`
}

func (q *Queries) UpdateChannelStatus(ctx context.Context, arg UpdateChannelStatusParams) error {
	_, err := q.db.Exec(ctx, updateChannelStatus, arg.ID, arg.Status, arg.LastError)
	return err
}
