// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgstore

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Channel struct {
	ID                 uuid.UUID          `json:"id"`
	OrgID              uuid.UUID          `json:"org_id"`
	PropertyID         uuid.UUID          `json:"property_id"`
	ConnectionID       uuid.UUID          `json:"connection_id"`
	Provider           string             `json:"provider"`
	ExternalPropertyID string             `json:"external_property_id"`
	Status             string             `json:"status"`
	LastSyncAt         pgtype.Timestamptz `json:"last_sync_at"`
	LastError          *string            `json:"last_error"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
}

type Connection struct {
	ID         uuid.UUID          `json:"id"`
	OrgID      uuid.UUID          `json:"org_id"`
	Provider   string             `json:"provider"`
	Name       string             `json:"name"`
	Status     string             `json:"status"`
	SecretRef  *string            `json:"secret_ref"`
	Config     []byte             `json:"config"`
	LastSyncAt pgtype.Timestamptz `json:"last_sync_at"`
	LastError  *string            `json:"last_error"`
	CreatedAt  time.Time          `json:"created_at"`
	UpdatedAt  time.Time          `json:"updated_at"`
}

type SyncJob struct {
	ID           uuid.UUID          `json:"id"`
	OrgID        uuid.UUID          `json:"org_id"`
	ConnectionID uuid.UUID          `json:"connection_id"`
	JobType      string             `json:"job_type"`
	Status       string             `json:"status"`
	Payload      []byte             `json:"payload"`
	Result       []byte             `json:"result"`
	Attempts     int32              `json:"attempts"`
	LastError    *string            `json:"last_error"`
	ScheduledAt  time.Time          `json:"scheduled_at"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}
