// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createConnection = `-- name: CreateConnection :one
INSERT INTO connections
    (
    id, org_id, provider, name, status, secret_ref, config
    )
VALUES
    (
        $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, org_id, provider, name, status, secret_ref, config, last_sync_at, last_error, created_at, updated_at
`

type CreateConnectionParams struct {
	ID        uuid.UUID `json:"id"`
	OrgID     uuid.UUID `json:"org_id"`
	Provider  string    `json:"provider"`
	Name      string    `json:"name"`
	Status    string    `json:"status"`
	SecretRef *string   `json:"secret_ref"`
	Config    []byte    `json:"config"`
}

func (q *Queries) CreateConnection(ctx context.Context, arg CreateConnectionParams) (Connection, error) {
	row := q.db.QueryRow(ctx, createConnection,
		arg.ID,
		arg.OrgID,
		arg.Provider,
		arg.Name,
		arg.Status,
		arg.SecretRef,
		arg.Config,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.Name,
		&i.Status,
		&i.SecretRef,
		&i.Config,
		&i.LastSyncAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSyncJob = `-- name: CreateSyncJob :exec
INSERT INTO sync_jobs
    (
    id, org_id, connection_id, job_type, status, payload, scheduled_at
    )
VALUES
    (
        $1, $2, $3, $4, $5, $6, $7
)
`

type CreateSyncJobParams struct {
	ID           uuid.UUID `json:"id"`
	OrgID        uuid.UUID `json:"org_id"`
	ConnectionID uuid.UUID `json:"connection_id"`
	JobType      string    `json:"job_type"`
	Status       string    `json:"status"`
	Payload      []byte    `json:"payload"`
	ScheduledAt  time.Time `json:"scheduled_at"`
}

func (q *Queries) CreateSyncJob(ctx context.Context, arg CreateSyncJobParams) error {
	_, err := q.db.Exec(ctx, createSyncJob,
		arg.ID,
		arg.OrgID,
		arg.ConnectionID,
		arg.JobType,
		arg.Status,
		arg.Payload,
		arg.ScheduledAt,
	)
	return err
}

const deleteConnection = `-- name: DeleteConnection :exec
DELETE FROM connections WHERE id = $1
`

func (q *Queries) DeleteConnection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteConnection, id)
	return err
}

const getConnectionByID = `-- name: GetConnectionByID :one
SELECT id, org_id, provider, name, status, secret_ref, config, last_sync_at, last_error, created_at, updated_at
FROM connections
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetConnectionByID(ctx context.Context, id uuid.UUID) (Connection, error) {
	row := q.db.QueryRow(ctx, getConnectionByID, id)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.Name,
		&i.Status,
		&i.SecretRef,
		&i.Config,
		&i.LastSyncAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSyncJobByID = `-- name: GetSyncJobByID :one
SELECT id, org_id, connection_id, job_type, status, payload, result, attempts, last_error, scheduled_at, started_at, finished_at, created_at, updated_at
FROM sync_jobs
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSyncJobByID(ctx context.Context, id uuid.UUID) (SyncJob, error) {
	row := q.db.QueryRow(ctx, getSyncJobByID, id)
	var i SyncJob
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ConnectionID,
		&i.JobType,
		&i.Status,
		&i.Payload,
		&i.Result,
		&i.Attempts,
		&i.LastError,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConnectionsByOrg = `-- name: ListConnectionsByOrg :many
SELECT id, org_id, provider, name, status, secret_ref, config, last_sync_at, last_error, created_at, updated_at
FROM connections
WHERE org_id = $1
ORDER BY created_at
`

func (q *Queries) ListConnectionsByOrg(ctx context.Context, orgID uuid.UUID) ([]Connection, error) {
	rows, err := q.db.Query(ctx, listConnectionsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connection{}
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Provider,
			&i.Name,
			&i.Status,
			&i.SecretRef,
			&i.Config,
			&i.LastSyncAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentSyncJobsByConnection = `-- name: ListRecentSyncJobsByConnection :many
SELECT id, org_id, connection_id, job_type, status, payload, result, attempts, last_error, scheduled_at, started_at, finished_at, created_at, updated_at
  FROM sync_jobs
 WHERE connection_id = $1
 ORDER BY created_at DESC
 LIMIT $2
`

type ListRecentSyncJobsByConnectionParams struct {
	ConnectionID uuid.UUID `json:"connection_id"`
	Limit        int32     `json:"limit"`
}

func (q *Queries) ListRecentSyncJobsByConnection(ctx context.Context, arg ListRecentSyncJobsByConnectionParams) ([]SyncJob, error) {
	rows, err := q.db.Query(ctx, listRecentSyncJobsByConnection, arg.ConnectionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncJob{}
	for rows.Next() {
		var i SyncJob
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ConnectionID,
			&i.JobType,
			&i.Status,
			&i.Payload,
			&i.Result,
			&i.Attempts,
			&i.LastError,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConnectionLastSync = `-- name: UpdateConnectionLastSync :exec
UPDATE connections
SET last_sync_at = $2, updated_at = now()
WHERE id = $1
`

type UpdateConnectionLastSyncParams struct {
	ID         uuid.UUID          `json:"id"`
	LastSyncAt pgtype.Timestamptz `json:"last_sync_at"`
}

func (q *Queries) UpdateConnectionLastSync(ctx context.Context, arg UpdateConnectionLastSyncParams) error {
	_, err := q.db.Exec(ctx, updateConnectionLastSync, arg.ID, arg.LastSyncAt)
	return err
}

const updateConnectionName = `-- name: UpdateConnectionName :exec
UPDATE connections
SET name = $2, updated_at = now()
WHERE id = $1
`

type UpdateConnectionNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateConnectionName(ctx context.Context, arg UpdateConnectionNameParams) error {
	_, err := q.db.Exec(ctx, updateConnectionName, arg.ID, arg.Name)
	return err
}

const updateConnectionStatus = `-- name: UpdateConnectionStatus :exec
UPDATE connections
SET status = $2, last_error = $3, updated_at = now()
WHERE id = $1
`

type UpdateConnectionStatusParams struct {
	ID        uuid.UUID `json:"id"`
	Status    string    `json:"status"`
	LastError *string   `json:"last_error"`
}

func (q *Queries) UpdateConnectionStatus(ctx context.Context, arg UpdateConnectionStatusParams) error {
	_, err := q.db.Exec(ctx, updateConnectionStatus, arg.ID, arg.Status, arg.LastError)
	return err
}

const updateSyncJobStatus = `-- name: UpdateSyncJobStatus :exec
UPDATE sync_jobs
SET status = $2, result = $3, last_error = $4, finished_at = now(), updated_at = now()
WHERE id = $1
`

type UpdateSyncJobStatusParams struct {
	ID        uuid.UUID `json:"id"`
	Status    string    `json:"status"`
	Result    []byte    `json:"result"`
	LastError *string   `json:"last_error"`
}

func (q *Queries) UpdateSyncJobStatus(ctx context.Context, arg UpdateSyncJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateSyncJobStatus,
		arg.ID,
		arg.Status,
		arg.Result,
		arg.LastError,
	)
	return err
}
